pexpect/pexpect

- pexpect/async.py
> Fix async expect when data was already read

- doc/overview.rst
Fix "bugs" in pexpect/doc/overview.rst
> Escape quote in print() and fix indexes

- pexpect/pty_spawn.py
Closes issue #190: __interact_copy implements
its own read() and write() calls, circumventing
the self._log() system, and omitting to log data
that is sent to the child pty.
Related, resolve old docstring about a setlog()
method that was removed in SpawnBase refactor.
> interact logs by self._log(s, 'read') and 'send'

- doc/history.rst
- pexpect/pty_spawn.py
Duplicates https://github.com/pexpect/pexpect/pull/266 to resolve the merge conflicts.
> Change ignore_sighup default to False

- pexpect/pty_spawn.py
> Encode command line args for unicode-mode spawn

- MANIFEST.in
> Include .coveragerc in pypi download tarball

- setup.py
> Add bashrc.sh to package_data

- doc/commonissues.rst
- pexpect/pty_spawn.py
- tests/test_delay.py
Yet another micro-optimization.
> Allow delaybeforesend=None to skip the sleep completely

- examples/passmass.py
> fix passmass example

- pexpect/popen_spawn.py
- pexpect/utils.py
Avoid passing None, which causes it to read from stdin.
Closes gh-433
> Only pass strings to shlex

- examples/astat.py
- examples/chess.py
- examples/chess3.py
- examples/df.py
- examples/monitor.py
- examples/topip.py
- examples/uptime.py
- pexpect/replwrap.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> Python 3.6 invalid escape sequence deprecation fixes

- pexpect/bashrc.sh
ubuntu: /etc/bash.bashrc
centos: /etc/bashrc
nixos: /etc/bashrc
> handle more OSes

- pexpect/pty_spawn.py
> Ensure spawn.closed gets set, improve sigwinch_passthrough example

- pexpect/pxssh.py
> Bug fix for SSH config file option

- pexpect/pty_spawn.py
Close https://github.com/pexpect/pexpect/issues/517
> interact: Add Python 3 compatibility warning

- doc/api/pxssh.rst
- pexpect/__init__.py
As per #514, I'm finally happy with this library enough to call it stable.
It needs a little work around unit tests and I probably  need to clean the code a little bit but the code is mature enough that someone other than me could use it as I'm not finding bugs in the library code and more bugs in what ever I've hacked up to use it.
> Add doc note about new expect based SSH automation library

- tests/test_socket.py
Fix test failures on IPv6-only machines.
> Use IPv6 loopback if there is no IPv4 loopback available

- examples/hive.py
> Fix simple typo: expcet -> except

- pexpect/run.py
The example code was not shown as code.
> fix run's docstring.

- examples/terminal_emulation.py
Example of how to use Pexpect and Pyte. See #587 .
> Examples of how to use Pexpect and Pyte (issue #587)

- tests/test_expect.py
- tests/test_socket.py
Fixes https://github.com/pexpect/pexpect/issues/807
> Tests: Avoid the multiprocessing forkserver method
