pexpect/pexpect

pexpect/__init__.py

It has been implemented for 2.x version but not 3.x.

Fix issue 126 for 3.x branch

---

doc/history.rst
pexpect/__init__.py
tests/test_run.py

For your quick review, @takluyver: This supersedes PR #177 and closes issue #176.
**major**
- bumps ``__version__`` to 4.0.dev as discussed in https://github.com/pexpect/pexpect/issues/174
- allows a method to be used as an event callback for ``run()``
**minor**
- better TypeError for invalid callback types
- more coverage to include this TypeError, ``test_run_event_typeerror``
- enhance readability of ``test_run.py``

Support MethodType as callback for pexpect.run(event=...)

---

doc/history.rst
pexpect/pty_spawn.py
setup.py
tests/test_isalive.py

This matches the same branch of ptyprocess, https://github.com/pexpect/ptyprocess/pull/18 from @reynir, ``noexception-on-wait-after-terminate``, which allows calling the wait() method multiple times without raising an exception.
There is no logical change, only a docstring and adjustments to (otherwise failing) test cases.
(@takluyver:  Note that TeamCity comprehends "pairing branch names" across these two repositories and tests them accordingly, but Travis-CI does not (so the test will fail, here). Created issue #210 to address.
Furthermore, described in https://github.com/pexpect/pexpect/commit/4bd7305df7a582887db7202128f285a2970aca6f it is now necessary to specify ``>=0.5`` requirement of ptyprocess.  In this particular case, It isn't terribly harmful, but it is good to start.  This …

Do not raise Exception on wait() after terminate or previous wait()

---

pexpect/replwrap.py

check basestring instead of str, which rejects unicode on py2
The failure is a bit odd, since instead of a TypeError, it gives:
AttributeError: 'unicode' object has no attribute 'echo'
since it passes through `self.child = str_cmd`

accept unicode cmd on Python 2

---

doc/api/pexpect.rst
pexpect/__init__.py
pexpect/async.py
pexpect/pty_spawn.py
pexpect/spawnbase.py

As discussed, this makes unicode vs. bytes two modes within spawn, rather than separate classes. There are various spawn classes for other purposes, and we were heading towards having fiddly multiple inheritance to get pxsshu, fdspawnu, etc.
I've left `spawnu` and `runu` as wrapper functions for backwards compatibility, but marked them deprecated and removed them from docs. They could alternatively be left as convenience functions: `spawnu(...)` is a bit less typing than `spawn(..., encoding='utf-8')`. I don't have a strong preference on this, but I've left updating the tests until we make a decision on this.
Also still to do: expose the encoding & codec_errors parameters on pxssh, fdspawn, and anything else that may need them.
Testing this requires the corresponding branch of ptyprocess …

'Unicode mode' in spawn class

---

pexpect/fdpexpect.py

Closes gh-174
I'm adding these back for compatibility, but I don't want to document them or encourage their use - if you're working with an fd, I think it's clearer to use os.write() directly rather than Pexpect's wrappers.
I haven't added sendintr, sendeof or sendcontrol, because I don't think they really make sense for a general fd, and you can easily do the equivalent things explicitly if you need to.

Restore send/write methods to fdpexpect

---

ANSI.py
FSM.py
fdpexpect.py
pxssh.py
screen.py
setup.py

These were deprecated in 3.x, moving them into the Pexpect package. This removes them entirely for 4.x.

Remove separate top-level modules

---

pexpect/fdpexpect.py
pexpect/pty_spawn.py
pexpect/pxssh.py

Allows them to provide a unicode interface in the same manner as spawn.
Merging this will close #92, #169 and #172.

Encoding parameters for pxssh and fdspawn

---

doc/FAQ.rst

Noah's pexpect, as long as I can remember, was
the popular vote for a python expect implementation,
this entry no longer relevant.

Remove FAQ entry about other python expect efforts

---

doc/commonissues.rst

This is no longer a problem, we've added p.isalive()
assertions to a great majority of our test cases
across a great many platforms of varying speeds that
contradicts this recommendation.

Remove 'add sleep before isalive()' recommendation

---

pexpect/pty_spawn.py

This has no change, both this method and ptyprocess
method signatures match 'True' value.

Honor 'force=False' when set on p.close()

---

tests/test_unicode.py
tests/test_which.py

Add two test cases. One to ensure which() can match a unicode filename, and another to ensure 'argument splitting' over unicode works fine and is received by the child process in the expected encoding.

Unicode argv tests

---

doc/FAQ.rst

First proposed in #163, to try to help tone down the number of general support requests.
Though I appreciate receiving feedback about the trickiest conditions of scripting a subprocess through a pseudo-terminal with pexpect, that pexpect might better explain by docstring or documentation, I would more appreciate such feedback in the form of a pull request!

suggest many alternatives for pexpect support

---

pexpect/popen_spawn.py
pexpect/pty_spawn.py
tests/test_popen_spawn.py

This will ultimately allow simple uses of Pexpect on Windows. Ping @blink1073 - I copied your gist for the implementation of this.
Open questions:
- At present, `__init__.py` imports `pty_spawn`, so you can't even load Pexpect on Windows. I started doing something along the lines of:
```python
if sys.platform == 'win32':
from .popen_spawn import PopenSpawn as spawn
else:
from .pty_spawn import spawn
```
But that didn't feel quite right; an apparently similar API would be doing something very different internally, which would doubtless lead to surprising bugs. Maybe on Windows the top-level package simply shouldn't have `spawn` and `spawnu`, and we'll leave them in place on Unix for backwards compatibility.
- I'm aiming to make it as close as possible to the applicable parts of the …

WIP: Add spawn class based on subprocess.Popen

---

pexpect/replwrap.py
tests/test_replwrap.py

* for multiple commands, such as in
``'\n'.join((cmd, cmd2))``, cmd2 and beyond
previously used a ``timeout`` of 1, instead of
the specified or default ``timeout``.
* furthermore, the output of multi-command output
was discarded, only the last-most command output
was received.  Resolved by joining the result of
``self.child.before``.

depricated: Resolve return value and timeout for multi-command and continuation prompts in replwrap

---

doc/api/fdpexpect.rst
doc/api/index.rst
doc/api/popen_spawn.rst
doc/history.rst
doc/install.rst
doc/overview.rst
pexpect/__init__.py
pexpect/fdpexpect.py
pexpect/popen_spawn.py
pexpect/pty_spawn.py
pexpect/replwrap.py
pexpect/run.py

I think this is the last major thing to do before releasing 4.0.
I'll give people a couple of days to look through this before I merge.

Make pexpect importable on Windows, and update docs

---

tests/test_unicode.py

test_unicode: don't need to format variable

---

MANIFEST.in

closes issue #280, where using replwrap for bash will likely result in error, because the dependent ``--rcfile=bashrc.sh`` is not found when pexpect is packaged.
Below is a diff to ensure correctness before and after commit:
```
--- /tmp/old	2015-10-06 10:31:28.000000000 -0700
+++ /tmp/new	2015-10-06 10:31:16.000000000 -0700
@@ -44,6 +44,7 @@
pexpect-4.1.dev/pexpect/__init__.py
pexpect-4.1.dev/pexpect/ANSI.py
pexpect-4.1.dev/pexpect/async.py
+pexpect-4.1.dev/pexpect/bashrc.sh
pexpect-4.1.dev/pexpect/exceptions.py
pexpect-4.1.dev/pexpect/expect.py
pexpect-4.1.dev/pexpect/fdpexpect.py
@@ -57,6 +58,7 @@
pexpect-4.1.dev/pexpect/spawnbase.py
pexpect-4.1.dev/pexpect/utils.py
pexpect-4.1.dev/PKG-INFO
+pexpect-4.1.dev/README.rst
pexpect-4.1.dev/setup.cfg
pexpect-4.1.dev/setup.py …
```

include pexpect/bashrc.sh, remove old entries

---

pexpect/async.py
tests/test_async.py

See Issue #286 -- there is a 2nd *new* error on MacOS for the new testcase, but I think it is the same as #213: a TIMEOUT was received instead of expected EOF.

Asyncio utf8 issue

---

.travis.yml
pexpect/async.py

Closes gh-213 (fingers crossed)
One symphony and several crazy theories later...
It looks like the problem was the asyncio event loop keeping a reference to the transport, which in turn keeps a reference to the protocol. So after an `expect(... async=True)` call had been made, the transport/protocol set up by that could keep reading events after the expect call had returned. A subsequent `expect(... async=True)` call sets up a new transport/protocol, but it misses events that have already been sent to the previous transport/protocol.
The solution, I hope, is to explicitly detach the transport from the event loop once we've found what we need by calling `transport.pause_reading()`. This makes the tests pass locally on Python 3.4.3.

Stop asyncio listening to pty once we've found what we need

---

pexpect/pty_spawn.py

Optimize `sendline()` by calling `send()` just once.

Call send() just once in sendline()

---

pexpect/pty_spawn.py
tests/test_repr.py

When subclassing ``spawn()``, or otherwise using ``command=None`` argument as in the given test, ``self.ptyproc`` is left unassigned resulting in exception, ``AttributeError: 'spawn' object has no attribute 'jptyproc'`` instead of ``TIMEOUT``.
Solution is to wrap access of this variable by ``hasattr``. Closes #298

Bugfix: AttributeError: 'spawn' object has no attribute 'ptyproc'

---

pexpect/pty_spawn.py

For use in SageMath, it is useful to be able to override some methods of the `PtyProcess` class. For this, we need to be able to customize the call `PtyProcess.spawn()` in pexpect.

Allow overriding the call to PtyProcess.spawn()

---

pexpect/expect.py
pexpect/spawnbase.py
tests/test_delay.py
tests/test_expect.py

The many calls to `time.sleep(0.0001)` in pexpect cause a serious performance loss when using pexpect in SageMath: that sleep was the main reason that SageMath was using pexpect-2.0 for a long time, see #215. And it seems that the releasing of the GIL during this sleep can also problematic, see #291.
To solve this problem, we make the sleep optional with a new `delayafterread` class attribute: if set to `None`, the sleep will be skipped completely (which is not the same as calling `time.sleep(0)`).

Add new ``delayafterread`` class attribute, for removing Superfluous sleep

---

pexpect/pty_spawn.py

Looking through [the doc](http://pexpect.readthedocs.org/en/stable/api/pexpect.html#spawn-class) several times, I missed the details of how to get the exit code of a spawned process.
Normally, important class attributes like `exitstatus` and `signalstatus` are called out in the docs with some kind of special formatting. Since I don't know how to do that here, I opted instead to add an example.

Provide example use of exitstatus and signalstatus

---

pexpect/expect.py
pexpect/pty_spawn.py

Without attaching it to the spawn object
Closes gh-345

Display current searcher in error messages

---

pexpect/pty_spawn.py
pexpect/utils.py
tests/test_env.py
tests/test_misc.py
tests/test_which.py

Currently pexpect.spawn takes an env argument along the lines of
subprocess.Popen but fails to use PATH from that env when finding
the binary to run.
The result when running a binary not on the PATH of the parent
process is pexpect will raise an exception, or worse, find a
different binary with the same name.
This change passes the env from spawn into the which function
so the correct PATH is searched and adds test coverage.

Use PATH from env argument to pexpect.spawn

---

LICENSE

Having "PEXPECT LICENSE" at the top of the file makes it seem like it is a custom license with specific terms, rather than the license of the Pexpect project. The text corresponds (as the header note righfully indicates) to the ISC License, so this change edits the header to hopefully clarify this.
Additionally, the formatting was slightly different from the standard ISC license template (as seen on https://opensource.org/licenses/isc-license or http://choosealicense.com/licenses/isc/), so the first paragraph was converted to regular sentence case rather than ALL CAPS like the disclaimer.

format license according to the standard template

---

pexpect/fdpexpect.py
pexpect/pty_spawn.py
pexpect/utils.py
tests/test_socket.py

Factor out uninterruptible select and put the code in utils as `select_ignore_interrupts`. Modify `fdpexpect` to use `select_ignore_interrupts` if `os.name` is `posix`. This should restore POSIX support without affecting Windows support.

Restore POSIX support to fdpexpect.

---

doc/history.rst
pexpect/fdpexpect.py

- bump version in documentation via pexpect/__init__.py
- describe PR #359 in changelog as regression
- minor docstring enhancements to fdspawn.read_nonblocking()

Prepare 4.2 release

---

pexpect/replwrap.py
tests/test_replwrap.py

From takluyver/bash_kernel#33 - if you run `env` or `echo $PS1` inside a replwrap bash, the output will contain the prompt string. Pexpect will think that is the prompt, cut off the output there, and then get into a confused state about the output of future commands.
This avoids that by inserting some characters `\[\]` which are displayed when inspecting the environment variable, but invisible when bash actually renders the prompt. This means that the output of `env` or `echo $PS1` doesn't match the prompt replwrap is looking for.
Those characters are intended to mark a set of non-printing characters (e.g. to change the terminal colour), so having them together as a pair should have no ill effects. I've verified in interactive testing that it works.

Fix running 'env' in replwrap-ed bash

---

pexpect/pxssh.py
tests/fakessh/ssh
tests/test_pxssh.py

This will cover the cases of connection refused, no route to host, and maybe some more. 
Currently the error is a bit hard to understand: 
```
Traceback (most recent call last):
File "/home/per/.homeassistant/deps/pexpect/spawnbase.py", line 144, in read_nonblocking
s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/per/.homeassistant/deps/pexpect/expect.py", line 97, in expect_loop
incoming = spawn.read_nonblocking(spawn.maxread, timeout)
File "/home/per/.homeassistant/deps/pexpect/pty_spawn.py", line 455, in read_nonblocking
return super(spawn, self).read_nonblocking(size)
File "/home/per/.homeassistant/deps/pexpect/spawnbase.py", line 149, in …
```

Raise proper exception when connection cannot be established

---

pexpect/pty_spawn.py

Update docstring for class `spawn.__init__` in pty_spawn.py to remove reference to deprecated spawnu in favour of spawn with ``encoding`` keyword argument
``spawnu`` deprecated according to line 805 of `pty_spawn.py` and issue #159

(minor) Remove spawnu in spawn docstring in favour of spawn with encoding arg

---

examples/README

Remove reference to missing sshls.py script in examples

Remove reference to missing script

---

pexpect/async.py
pexpect/spawnbase.py
tests/test_async.py

_UnixReadPipeTransport class closes pipe in __del__ method. This commit
adds attribute to SpawnBase with pointer to current transport.

dont remove reference to _UnixReadPipeTransport

---

pexpect/popen_spawn.py

The pid of the class PopenSpawn has always returned None because it was never assigned

added missing assignment of pid var to PopenSpawn class

---

pexpect/pxssh.py

In python 3.6 it raises a DeprecationWarning to have strings with invalid backslash escape sequences. Changing the strings to raw strings (that doesn't try to look for escape sequences) makes the intention clearer and shuts up the DeprecationWarning

Use raw strings for strings with literal backslash

---

pexpect/spawnbase.py
tests/test_async.py

Closes gh-315
`async=True` should still work as well, since some people are already using it.

Rename async= parameter to async_=

---

pexpect/pty_spawn.py

Pull request to solve issue described in https://github.com/pexpect/pexpect/issues/383.
//Kristopher

Raise ExceptionPexpect instead of PtyProcessError in spawn.close

---

pexpect/popen_spawn.py

[On win32 Popen uses strings for args](https://docs.python.org/3/library/subprocess.html#converting-argument-sequence), so in PopenSpawn it isn't necessary to convert a string to a list just for Popen to convert it back again.
This also resolves an issue I was having where if the path to the executable was double quoted those quotes would stay in the first element of the cmd list and would cause Popen to throw a FileNotFoundError.

Don't split cmd strings on win32 in PopenSpawn

---

pexpect/pxssh.py

pxssh checks for 'password' as the password prompt rather than 'password:'. This breaks things when the word 'password' is in the banner - which is rather more common than you might think. I think what is happening is, pxssh is sending the password, but then seeing the word 'password' in the banner and thinking that it has failed to log in.
This extremely simple fix should work, as long as:
1. There aren't any legitimate instances where SSH will prompt for password without a colon (I have never observed this)
2. It still doesn't cover the case where the banner actually contains the word password followed by a colon - "password:" - handling this would require a more substantial change.
I would respectfully suggest consideration of merging this pull request unless there are legitimate known …

Issue #451: Check for "password:" as prompt instead of "password"

---

pexpect/bashrc.sh

People may use PROMPT_COMMAND to modify the prompt (hat-tip to @Naereen, who does). Unset it to avoid breaking replwrap.
The line between customisations that people might want to be preserved in replwrap (like aliases) and those that don't make sense (like custom prompts) is somewhat indistinct. But from the uses of PROMPT_COMMAND I've seen, I think it's more likely that it shouldn't apply in replwrap.

Unset PROMPT_COMMAND in bash for replwrap

---

pexpect/_async.py
pexpect/expect.py
pexpect/pty_spawn.py
pexpect/spawnbase.py
tests/test_expect.py
tests/test_performance.py

Python strings are slow and expensive as buffers because they're immutable;
replace the output buffer with a `StringIO/BytesIO` object
see: https://github.com/pexpect/pexpect/issues/438
see: https://github.com/pexpect/pexpect/issues/385
see: https://github.com/pexpect/pexpect/issues/352

optimize pty buffering and searching

---

pexpect/expect.py
tests/test_misc.py

I was getting:
0: re.compile("b'^[^\r\n]*\r?\n'")
1: re.compile("b'^--More-- or \\(q\\)uit'")
2: re.compile("b'^\\(.*\\) #'")
So I decided to drop the `%s` and keep only the `%r`, which works equally for
str and bytes:
>>> '    %d: re.compile(%r)' % (1, b'foo')
"    1: re.compile(b'foo')"
>>> '    %d: re.compile(%r)' % (1, 'foo')
"    1: re.compile('foo')"

FIX: bad representation of bytes patterns.

---

pexpect/pxssh.py

Patch that allows setting some custom regexes for pxssh and allows pxssh to be more gentle with target SSH servers and the shells they spawn.
This is for #451
Please let me know if I need to change anything in regards to docs or comments and those requests will be handled.

Add custom regexes and allow for delicate SSH servers

---

pexpect/pxssh.py

I had to backport in a command line sanitizer from shlex.quote so that python2 would function correctly with no shell injection.

Add SSH tunneling to pxssh

---

pexpect/_async.py
pexpect/expect.py
tests/test_expect.py

see: https://github.com/pexpect/pexpect/issues/478

fix a bug causing 'spawn.before' to be truncated w/ searchwindowsize use

---

.gitignore
doc/conf.py
doc/history.rst
pexpect/__init__.py
pexpect/fdpexpect.py
pexpect/pty_spawn.py
pexpect/utils.py
setup.cfg
setup.py
tests/test_misc.py
tests/test_socket.py

- Add the use_poll bool for callers to choose if they want poll
- This ensure we leave the default as it is today
- Added unit tests to use select.poll()
- Updated documentation guessing format etc.
If wrong I can fix, or if you could just fix post merge that would be amazing :D

Allow callers to enable to use of select.poll()

---

pexpect/fdpexpect.py
pexpect/pty_spawn.py
pexpect/utils.py

Like select.select() call and fix broken __interact_copy implementation

Make poll_ignore_interrupts register multiple FDs

---

pexpect/popen_spawn.py
tests/test_popen_spawn.py

Make `crlf` match the default platform behaviour in `PopenSpawn`.

---

pexpect/utils.py
tests/test_misc.py

see: https://github.com/pexpect/pexpect/issues/491

properly handle read timeouts with use_poll=True

---

pexpect/pxssh.py
tests/test_pxssh.py

As per the title, this is for issues #489 and #429.
@takluyver it might be a good idea to do a docs update from commit 6b741f9 as this will solve a small piece of miscommunication I introduced by doing doc updates for my own additions but not for pre-existing features.

Update docs and add SSH config file passing

---

pexpect/_async.py
pexpect/replwrap.py
tests/test_async.py
tests/test_replwrap.py

Add an 'async_' argument to run_command. When True, a Future object will
be returned which *must* be awaited in asynchronous code.
Signed-off-by: Robin Jarry <robin.jarry@6wind.com>
Signed-off-by: Thomas Faivre <thomas.faivre@6wind.com>

replwrap: add async support

---

pexpect/pty_spawn.py

Optimize `read_nonblocking()` in two ways:
1. When a lot of data is available to read, return all of it. This speeds up callers of `read_nonblocking()` such as `expect_loop()` because there are a lot less iterations in the loop.
2. Only call `is_alive()` if there is no data ready to read. This avoids a lot of pointless calls to `is_alive()`.
Downstream: http://trac.sagemath.org/ticket/10295

Read more bytes

---

tests/test_expect.py

Pipe like "openssl rand -base64 2097152 | head -n 500" leads to "Broken pipe"
error on some systems. This is an unexpected behavior. So errors must be
suppressed.
Fixes: https://github.com/pexpect/pexpect/issues/523

Fix "test_before_across_chunks" test

---

tests/test_replwrap.py

Due to an old bash version(3.x) on some systems there is no builtin "time"
command. Another more common one can be used for.
Fixes: https://github.com/pexpect/pexpect/issues/521

Fix "test_bash" test

---

.travis.yml

3.3 is EOL and 3.7 requires special handling on Travis.

Travis CI: Remove Python 3.3 and add Python 3.7

---

pexpect/pxssh.py

Add the use_poll option to use pxssh with >1024 FDs.

add use_poll to pxssh

---

pexpect/pxssh.py

This can be very useful if you want to run the pxssh client in a network namespace.

Allow customized pxssh client

---

pexpect/pxssh.py
tests/fakessh/ssh
tests/test_pxssh.py

As requested, test cases were added for the feature request to enable customized ssh command for pxssh.

Allow customized pxssh client #528

---

pexpect/pxssh.py
tests/test_pxssh.py

If pxssh.login is called with an ssh_config then do not require username since it can be supplied via the config and some programs do not want to manage the username at all since it would require parsing the ssh config.
This commit removes the independent username parameter when formatting cmd and instead appends the flag and the username to ssh_options if a username is provided.
If neither username nor ssh_config is provided raise a TypeError in line with the error raised natively if username was not provided as a required positional argument.

pxssh.login require either username or ssh_config

---

doc/commonissues.rst

When reading the documentation of the 'commonissues', I was a little confused:
the documentation mentioned 'the delaybeforesend attribute of the spawn class'.
Since classes are actual things that can have attributes, it contradicts the example
of two lines below.
This MR rectifies this small inconsistency.

Docs: distinguish class attributes and object attributes

---

tests/test_ansi.py

Minor fix, test_ansi causes ANSI.py's DoLog to write to cwd.
If the test directory is not writable, this fails.  It should run from a tempdir.

Fix test_ansi.py when running in a non-writable directory

---

tests/test_expect.py

This is broken for Python3, but the routine is only called on test failure, so it doesn't cause the Python3 tests to fail.

s/xrange/range/ for Python3

---

tests/test_which.py

On systems with ascii filesystem encoding, don't attempt to use unicode paths in the test.

Fix test_which when sys.getfilesystemencoding() is ascii

---

tests/interact.py
tests/test_async.py
tests/test_ctrl_chars.py
tests/test_interact.py
tests/test_isalive.py
tests/test_misc.py
tests/test_pxssh.py
tests/test_run.py

Support cases where self.PYTHONBIN != sys.executable, by consistently using self.PYTHONBIN in tests.  Then, anyone who has a problematic value for sys.executable only needs to edit PexpectTestCase in a local patch (much smaller local patch to maintain).

Always use self.PYTHONBIN not 'python' or sys.executable in tests

---

pexpect/expect.py

The code works in Python 2.x and 3.x but it should be replaced by "raise
exception from other-exception" when the support for Python 2.x gets
dropped.
See issue #605

Disable chaining Timeout and EOF exceptions

---

setup.py

- bug tracker
- documentation
- source code
These will be shown at the project's PyPi page ( https://pypi.org/project/pexpect/ ) and make it easier to find relevant information.

Add project urls to `setup.py`

---

doc/overview.rst

Wexpect is a maintained (almost for a year) alternative of pexpect for Windows.
- All (non-Linux specific) pexpect testcases passes with
- ~80% coverage

Update doc: Wexpect is maintained

---

pexpect/replwrap.py
tests/test_performance.py
tests/test_replwrap.py
tests/test_run.py

This makes sure the tests and wrapper works on systems where there
is no python2 nor /usr/bin/python available

Do not directly call python and use sys.executable

---

tests/test_replwrap.py

The test test_bash_env() relies on PS1 being an environment variable.
Therefore, `export PS1` making it always an environment variable.
Before this, the test relied on the users bashrc to do this.
The variable PS1 is (by default) not an _environment_ variable and thus
not shown by `env`. Any variable can be made into an environment
variable by exporting it. Some people do this for PS1 in their bashrc.
Closes: #631

REPLWrapTestCase.test_bash_env(): export variable PS1

---

pexpect/popen_spawn.py

Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

---

tests/test_replwrap.py

On Solaris (and possibly other systems as I don't think this is standardized), the `sleep` manual page uses a lowercase name in the header, hence `SLEEP` is not found.
After this change, the test case will look for the section name, which AFAICT is always uppercase.
Alternatively, the `assert` can be changed to something like this:
`assert 'SLEEP' in res.upper(), res`
EDIT: The section name approach doesn't work (not sure why it seemed to work yesterday), so I changed it to the `res.upper()` approach instead. Thinking about that now, it is more robust and platform independent as well.

fix `test_pager_as_cat` test case on Solaris

---

pexpect/spawnbase.py
tests/test_expect.py

This change fixes [issue 558](https://github.com/pexpect/pexpect/issues/558) by extending the type coercing already present in exact matches for compiled regex matches. In short: if spawn encoding is None, it changes the compiled regex to have a bytes type pattern. Otherwise, changes to non-bytes type pattern.

[Issue #558] Coerce compiled regex patterns type according to spawn encoding

---

requirements-testing.txt

The `pytest-capturelog` plugin no longer exists; its functionality has been merged into the pytest core since ~3.3. Remove the dependency.
Fixes #729

Remove `pytest-capturelog` from testing requirements

---

tests/test_interact.py

These tests have the same issues on GitHub Actions, so switch to use the more generic 'CI' variable to detect when being run on a CI platform to handle these tests properly.

test_interact: update Travis overrides to use generic CI variable

---

tests/PexpectTestCase.py
tests/test_expect.py
tests/test_misc.py
tests/test_popen_spawn.py

unittest.TestCase.assertRaisesRegexp was deprecated in Python 3.2 and is removed in Python 3.12.

tests: Replace assertRaisesRegexp with assertRaisesRegex

---

tests/deprecated_test_filedescriptor.py
tests/deprecated_test_run_out_of_pty.py
tests/test_ansi.py
tests/test_command_list_split.py
tests/test_constructor.py
tests/test_ctrl_chars.py
tests/test_destructor.py
tests/test_dotall.py
tests/test_expect.py
tests/test_filedescriptor.py
tests/test_interact.py
tests/test_isalive.py
tests/test_log.py
tests/test_misc.py
tests/test_missing_command.py
tests/test_performance.py
tests/test_popen_spawn.py
tests/test_screen.py
tests/test_socket.py
tests/test_timeout_pattern.py
tests/test_unicode.py
tests/test_winsize.py

This function was never formally documented, but has been deprecated and will be removed in Python 3.13.  Replaced with unittest.TestLoader.loadTestsFromTestCase.

Replace deprecated unittest.makeSuite

---

tests/test_run.py

The `--rcfile` option to bash does not prevent the system-wide `/etc/bash.bashrc` script from running (contrary to the Debian man-page). This causes `test_run.py` to fail when the system-wide script produces output (as is the case in an Ubuntu image where the regular user belongs to the "sudo" group and the system-wide script produces an informational message about `sudo` usage).
Rather than rely on `--rcfile`, this patch changes the test to use `--norc` (which does suppress the execution of the system-wide bashrc), and changes `PS1` via the inherited environment instead (this also slightly simplifies the fixture setup too as `tempfile` is no longer required).

Ensure test_run.py works when system-wide bashrc produces output

---

pexpect/_async.py
pexpect/_async_pre_await.py
pexpect/_async_w_await.py
tests/test_async.py

Python 3.5 introduced the await and async def keywords. This change imports the coroutines from two different places, depending on the running Python version.
This address comments previously put in pull requests:
- #715 
- #690 
-

refactor(_async.py): introduce modern coroutine syntax

---

pexpect/__init__.py

Add an example to the docs of how to use spawn() function with context manager.
https://github.com/pexpect/pexpect/issues/727

Update docs to use context manager

---

pexpect/bashrc.sh
tests/PexpectTestCase.py
tests/test_expect.py
tests/test_misc.py
tests/test_popen_spawn.py
tests/test_replwrap.py

Linux specific commands ans options are used in the test_before_across_chunks function (/bin/bash; nl with long options) which make this test fail on generic POSIX systems. No bash specific features or GNU nl features are used, therefore it is easily possible to make the test run on any POSIX system.
There was an assumption that STDIO buffers are large enough to hold some 10 KB of data. I assume that these buffers are 16 KB on Linux by default, but this is not true for other POSIX systems. The default STDIO buffer size is 4 KB on FreeBSD, for example, which leads to "cat" being blocked waiting to drain its output buffer before it accepts any further input.
The test does not depend on any particular amount of data or characters per line, therefore lines of 39 text characters plus line end …

Make test_expect.py work on POSIX systems that are not Linux based

---

.github/workflows/ci.yml
requirements-testing.txt
tests/PexpectTestCase.py
tests/test_async.py

Closes https://github.com/pexpect/pexpect/issues/752
Request by @Red-M (https://github.com/pexpect/pexpect/pull/732#issuecomment-1466243877) is to rework the async tests to rely on unittest.IsolatedAsyncioTestCase

rework async unittests to rely on unittest.IsolatedAsyncioTestCase

---

.github/workflows/ci.yml

Closes #762
This adds:
- test against Python 3.5, 3.6 and 3.12.0-rc.1

Add Python 3.5, 3.6 and 3.12.0-rc.1 to test matrix

---

.github/workflows/ci.yml
.travis.yml
DEVELOPERS.rst
tests/README
tools/teamcity-runtests.sh

The [second Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
---
Python 3.7 is EOL and no longer receiving security updates (or any updates) from the core Python team.
| version |  released  |    eol     |
|:--------|:----------:|:----------:|
| 3.11    | 2022-10-24 | 2027-10-24 |
| 3.10    | 2021-10-04 | 2026-10-04 |
| 3.9     | 2020-10-05 | 2025-10-05 |
| 3.8     | 2019-10-14 …

Add support for Python 3.12

---

pexpect/replwrap.py
tests/test_replwrap.py

Python 3.13+ has colors now. Always setting this variable should be safe.

Force NO_COLOR=1 to fix test failures with Python 3.13+ REPL
